# Generated by Django 5.1 on 2024-08-18 12:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('updated', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'pending'), ('r', 'released')], max_length=1)),
                ('authors', models.ManyToManyField(related_name='authored_books', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(related_name='books', to='books.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
