# Generated by Django 5.1 on 2024-09-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_chapter_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('chapter', 'page_number')},
        ),
    ]
