# Generated by Django 5.1 on 2024-09-29 12:47

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_book_cover),
        ),
    ]
