# Generated by Django 5.1 on 2024-11-22 17:10

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
