# Generated by Django 5.1 on 2024-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2048)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_read', 'id'],
            },
        ),
    ]
